alarm:
  servernickname: "server1"
  telegram:
    enabled: true
    token: "123456789:ABCDEF"
    chatid: "-123456789"
    MessageThreadID: 1
  slack:
    enabled: true
    webhookurl: "http://example.com/webhook"
    
api:
  host: localhost
  port: 8080

disk:
  filesystems: ["ext2", "ext3", "ext4", "xfs", "btrfs", "zfs"]
  partuselimit: 90
  checkinterval: 5
  unit: "GB"

cpu:
  loadlimit: 4
  checkinterval: 5

memory:
  uselimit: 90
  checkinterval: 5
  unit: "GB"

network:
  interfaces: ["eth0", "eth1"]
  checkinterval: 5